version: 2

updates:
  # ── GitHub Actions (workflow steps) ──────────────────────────────
  - package-ecosystem: "github-actions"
    directory: "/"                # scans .github/workflows
    schedule:
      interval: "weekly"

  # ── Local action in .github/actions/test ────────────────────────
  - package-ecosystem: "npm"
    directory: "/.github/actions/test"
    schedule:
      interval: "daily"

  # ── foundry‑tracing‑foundations package ─────────────────────────
  - package-ecosystem: "npm"
    directory: "/foundry-tracing-foundations"
    schedule:
      interval: "daily"

  # ── hello‑world package ─────────────────────────────────────────
  - package-ecosystem: "npm"
    directory: "/hello-world"
    schedule:
      interval: "daily"

  # ── x‑reason‑node package ───────────────────────────────────────
  - package-ecosystem: "npm"
    directory: "/x-reason-node"
    schedule:
      interval: "daily"
